### ISSUE TITLE
Styling grid cells?

### ISSUE THREAD

**Issue by dement-construction** [alonrbar/react-tablize#4]
Hi,  this looks great!  
Would it be possible for you to add a quick example on how to style a grid cell?

**Comment by alonrbar** [comment]
Thanks :)

I recommend you take a look at the following test files. Or even better, clone the repo and run `yarn test` to launch the storybook tests (in case you're unfamiliar with storybook: [link](https://storybook.js.org/)).

**Grid style example:** 
This [test](https://github.com/alonrbar/react-tablize/blob/master/test/stories/grid.stories.tsx#L18) uses [this function](https://github.com/alonrbar/react-tablize/blob/master/test/stories/grid.stories.tsx#L78) to render styled cells.

**Table style example:**
Check [this test](https://github.com/alonrbar/react-tablize/blob/master/test/stories/table.features.stories.tsx#L46) and [this test](https://github.com/alonrbar/react-tablize/blob/master/test/stories/table.features.stories.tsx#L68) for examples.

Notice that some of the examples uses direct `style` property while others uses the [emotion](https://emotion.sh/docs/styled) styling library. Both methods should work in all cases so you are free to choose whatever you personally prefer.

**Comment by alonrbar** [comment]
Closing this issue. If you need more help feel free to re-open.
