### ISSUE TITLE
Working example of Grid

### ISSUE THREAD

**Issue by znarkd** [alonrbar/react-tablize#7]
Could you put a working example on CodeSandbox or a similar environment?

When I try
`import Grid from "react-tablize"`

I get errors about emotion-theming

**Comment by alonrbar** [comment]
Hi,
Just tried it and getting the same error. It's probably some backward compatibility issue with the `emotion` package I use.  
Tried to resolved it but it turns out to be quite a pain. 
To resolve the issue I've decided to remove the `emotion` dependency entirely but it may take a while until I have time to complete the removal.
Will update again when it all works.

**Comment by alonrbar** [comment]
Here's a working sandbox:
https://codesandbox.io/s/react-tablize-example-45uxc

It uses version `2.2.0-next.0` that removed the `emotion` dependency.
I've tagged it "next" so installing requires explicitly stating the version number (like so `yarn add react-tablize@2.2.0-next.0`).
The reason it's a "next" version and not the stable "latest" version is that some small style features still needs porting ([here](https://github.com/alonrbar/react-tablize/blob/29a039cf39dc3c1ae8a9f43427b31277626b252e/src/table/TableCell.tsx#L39)).

**Comment by znarkd** [comment]
Thank you for the working example.  I noticed there is a scroll bounce effect on iOS devices.  Hoping that your style changes will fix that.

**Comment by alonrbar** [comment]
Don't have an iOS device at hand but tested in Chrome on Windows, Chrome on Android and Safari on a virtual mac. All looks fine.
The missing style "features" are just a few tweaks for padding and border when using the [table default style](https://github.com/alonrbar/react-tablize/blob/master/src/table/Table.tsx#L56). In fact the Grid component is fully implemented and should be working as intended.

I can try to get my hands on an iPhone from a friend, just trying to understand, is the bounce effect something you see specially with this library or is it something standard for scrolling in iOS?

**Comment by znarkd** [comment]
The scroll bounce is inherent in iOS.

**Comment by alonrbar** [comment]
In this case it seems reasonable that the grid will have the same bounce effect, isn't it?

**Comment by znarkd** [comment]
Some grids are able to limit the bounce to the main grid body only.  The
fixed headers and fixed columns don't move.  See
https://bvaughn.github.io/react-virtualized/#/components/ScrollSync

Your example from my iPhone:
https://drive.google.com/file/d/1bwDMxKVcrFD6Xk4BajMf8IqIG4TwznVN/view?usp=sharing

**Comment by alonrbar** [comment]
I see, interesting. I'll try to have a look see how this can be achieved.

**Comment by znarkd** [comment]
I think if you set the style for '_Container' divs to position: absolute with appropriate top and left values, that the fixed columns wouldn't bounce around on iOS devices.

**Comment by alonrbar** [comment]
Yes, I believe so. Haven't got the time to work on it but my plan is to expose a `sticky` property with three allowed values: `true`, `false` and "auto" which will be the default. It will then be read in this [line](https://github.com/alonrbar/react-tablize/blob/cf0abf726d7a50db611c51cb7431de8e945d023c/src/grid/Grid.tsx#L220). Feel free to fork and add it yourself in the meantime. If you do so I'll be happy to hear if it does solve the problem.

**Comment by alonrbar** [comment]
Oh, and by the way. The grid already accepts a 'style' property you can try to use as well.
